# render.yaml
services:
  - type: web
    name: bookingSystem
    env: java # Indica que es una aplicaci칩n Java (Spring Boot)
    branch: principal # La rama del repositorio que quieres desplegar
    buildCommand: "./mvnw clean install" # Comando para compilar tu aplicaci칩n (ajusta si usas Gradle)
    startCommand: "java -jar target/*.jar" # Comando para iniciar la aplicaci칩n
    plan: free # Plan que quieres usar (free, starter, etc.)
    healthCheckPath: "/" # Ruta para verificar si la app est치 activa
    envVars:
      - key: SPRING_APPLICATION_NAME
        value: bookingSystem
      - key: SPRING_DATA_MONGODB_URI
        value: mongodb+srv://localmakergrupo3:pocholis@cluster0.nbgj6.mongodb.net/BookSystem?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: mi_clave_secreta_larga_y_seguraxsssss
      - key: SPRING_PROFILES_ACTIVE
        value: prod # Ajusta el perfil si es necesario (prod, dev, etc.)

